import type { Metadata } from "next"
import "./globals.css"
import { ThemeProvider } from "@/components/theme/theme-provider"
import NavBar from "@/components/layout/NavBar"
import Footer from "@/components/layout/Footer"
import { TooltipProvider } from "@/components/ui/tooltip"
import { CircleAlert, CircleCheckBig, CircleX } from "lucide-react"
import { Toaster } from "@/components/ui/sonner"
import localFont from "next/font/local"

const rubik = localFont({
	src: "../../public/Rubik.ttf",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ar" dir="rtl" suppressHydrationWarning className={` h-full antialiased`}>
			<body className={`${rubik.className} min-h-full flex flex-col`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<NavBar />
					<TooltipProvider>
						<main className="min-h-svh">
							{children}
							<Toaster
								theme="system"
								richColors
								duration={5000}
								icons={{
									success: <CircleCheckBig />,
									warning: <CircleAlert />,
									error: <CircleX />,
								}}
							/>
						</main>
					</TooltipProvider>
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
